services:
  api:
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
  vectordb:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}