services:
  api:
    environment:
      - MONGO_URI=mongodb://clarisync-admin:August141947@host.docker.internal:27017/LibreChat?authSource=admin
    volumes:
      - ./librechat.yaml:/app/librechat.yaml